// Singleton audio manager. Lives outside React so background music is never
// re-created or restarted when components re-render or screens change.
//
// The audio files ship in /public/audio as .wav (generated by the included
// _generate.cjs script, all synthesized locally, no license concerns). To
// swap in your own music or effects, replace the files at:
//   /public/audio/music-theme.wav      looping background music
//   /public/audio/sfx-click.wav        button click
//   /public/audio/sfx-pickup.wav       piece picked up
//   /public/audio/sfx-place.wav        correct placement
//   /public/audio/sfx-wrong.wav        incorrect placement
//   /public/audio/sfx-complete.wav     level completed
//
// If any file is missing, playback errors are caught silently so the game
// still works.

const SFX_PATHS = {
  click: '/audio/sfx-click.wav',
  pickup: '/audio/sfx-pickup.wav',
  place: '/audio/sfx-place.wav',
  wrong: '/audio/sfx-wrong.wav',
  complete: '/audio/sfx-complete.wav',
};

const MUSIC_PATH = '/audio/music-theme.wav';

class AudioManager {
  constructor() {
    this.music = typeof Audio !== 'undefined' ? new Audio(MUSIC_PATH) : null;
    if (this.music) {
      this.music.loop = true;
      this.music.volume = 0.4;
      this.music.preload = 'auto';
    }
    this.sfxVolume = 0.7;
    this.musicOn = true;
    this.sfxOn = true;
  }

  applySettings({ musicOn, sfxOn, musicVolume, sfxVolume }) {
    this.musicOn = musicOn;
    this.sfxOn = sfxOn;
    this.sfxVolume = sfxVolume;
    if (this.music) {
      this.music.volume = musicVolume;
      if (musicOn) this.playMusic();
      else this.music.pause();
    }
  }

  playMusic() {
    if (!this.music || !this.musicOn) return;
    if (this.music.paused) {
      this.music.play().catch(() => {
        // browsers block autoplay until first user gesture, expected
      });
    }
  }

  isPlaying() {
    return !!this.music && !this.music.paused;
  }

  stopMusic() {
    if (this.music) this.music.pause();
  }

  playSfx(name) {
    if (!this.sfxOn) return;
    const src = SFX_PATHS[name];
    if (!src) return;
    try {
      const el = new Audio(src);
      el.volume = this.sfxVolume;
      el.play().catch(() => {});
    } catch {
      /* ignore */
    }
  }
}

export const audioManager = new AudioManager();
